# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Immo's Blog
tagline:          'Thoughts & Ideas'
description:      'Father. Husband. Coder. Microsoftie.'
url:              http://immo.landwerth.net

author:
  name:           'Immo Landwerth'
  url:            https://twitter.com/terrajobst

paginate:         5
