# Dependencies
markdown:         GFM
highlighter:      pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            terrajobst
tagline:          'Thoughts & Ideas'
description:      'Father. Coder. Microsoftie.'
url:              http://immo.landwerth.net

author:
  name:           'Immo Landwerth'
  url:            https://twitter.com/terrajobst

paginate:         5
